spring:
  application:
    name: WarehouseSimulator
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/warranty_tracker
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

warehouse:
  width: 20
  height: 20